# Generated by Django 5.1.6 on 2025-02-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_employee_alter_employee_citizen_id_and_more'),
        ('simcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importReceipt', to='accounts.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'importReceipt',
            },
        ),
        migrations.CreateModel(
            name='ImportReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('import_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.importreceipt')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importReceiptDetail', to='simcards.sim')),
            ],
            options={
                'db_table': 'importReceiptDetail',
                'unique_together': {('import_receipt', 'sim_id')},
            },
        ),
    ]
