# Generated by Django 5.1.6 on 2025-02-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importreceiptdetail',
            unique_together={('import_receipt', 'sim_id')},
        ),
    ]
