# Generated by Django 5.1.6 on 2025-02-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0002_alter_sim_export_price'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importreceiptdetail',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='importreceiptdetail',
            constraint=models.UniqueConstraint(fields=('import_receipt', 'sim'), name='unique_import_sim'),
        ),
    ]
