# Generated by Django 5.1.6 on 2025-02-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importreceipt',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
