# Generated by Django 5.1.6 on 2025-03-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_importreceiptdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='importreceipt',
            table='import_receipt',
        ),
        migrations.AlterModelTable(
            name='importreceiptdetail',
            table='import_receipt_detail',
        ),
    ]
