# Generated by Django 5.1.7 on 2025-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_importreceipt_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importreceiptdetail',
            name='import_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
