# Generated by Django 5.1.6 on 2025-02-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='export_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
