# Generated by Django 5.1.6 on 2025-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0003_sim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hết hàng'), (1, 'Có sẵn'), (2, 'Đang đăng bán')], default=1),
        ),
    ]
