# Generated by Django 5.1.6 on 2025-03-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0004_alter_sim_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category1',
            table='category_1',
        ),
        migrations.AlterModelTable(
            name='category2',
            table='category_2',
        ),
        migrations.AlterModelTable(
            name='mobilenetworkoperator',
            table='mobile_network_operator',
        ),
    ]
