# Generated by Django 5.1.6 on 2025-03-25 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0005_alter_category1_table_alter_category2_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', 'Số điện thoại không hợp lệ!')]),
        ),
    ]
