# Generated by Django 5.1.6 on 2025-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0006_alter_sim_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
