# Generated by Django 5.1.7 on 2025-04-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0008_remove_sim_created_at_remove_sim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='export_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
