# Generated by Django 5.1.6 on 2025-02-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=255),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=255),
        ),
    ]
