# Generated by Django 5.1.6 on 2025-02-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_employee_alter_employee_citizen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
        ),
    ]
