# Generated by Django 5.1.6 on 2025-02-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.role'),
        ),
    ]
