# Generated by Django 5.1.6 on 2025-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
