# Generated by Django 5.1.7 on 2025-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
