# Generated by Django 5.1.6 on 2025-02-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='created_by',
            new_name='employee',
        ),
    ]
