# Generated by Django 5.1.6 on 2025-03-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_status'),
        ('orders', '0003_rename_created_by_discount_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_methods',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_records', to='accounts.employee'),
        ),
        migrations.CreateModel(
            name='DetailUpdateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated', models.IntegerField(choices=[(0, 'Đã hủy'), (2, 'Đang giao hàng'), (3, 'Đã giao hàng')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_updates', to='accounts.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'detail_update_order',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('credit_card', 'Thẻ tín dụng'), ('bank_transfer', 'Chuyển khoản ngân hàng')], max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Đã thanh toán')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
