# Generated by Django 5.1.6 on 2025-03-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_payment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
