# Generated by Django 5.1.6 on 2025-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
