# Generated by Django 5.1.6 on 2025-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_discount_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
