# Generated by Django 5.1.7 on 2025-04-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_discount_status'),
        ('simcards', '0008_remove_sim_created_at_remove_sim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.BooleanField(choices=[(False, 'Chưa sử dụng'), (True, 'Đã sử dụng')], default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='simcards.sim'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Đã thanh toán'), (2, 'Thanh toán thất bại')], default=0),
        ),
    ]
